package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/budisuryadi/pgquerydoctor/internal/analyzer"
	"github.com/budisuryadi/pgquerydoctor/internal/report"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}
	switch os.Args[1] {
	case "analyze":
		runAnalyze(false)
	case "report":
		runAnalyze(true)
	case "lint":
		runLint()
	case "suggest-index":
		runSuggestIndex()
	case "version":
		fmt.Println("PgQueryDoctor v0.1.0")
	default:
		usage()
		os.Exit(1)
	}
}

func runAnalyze(writeReport bool) {
	fs := flag.NewFlagSet(os.Args[1], flag.ExitOnError)
	queryPath := fs.String("query", "", "Path to SQL query file")
	explainPath := fs.String("explain", "", "Path to EXPLAIN ANALYZE output file")
	outputPath := fs.String("output", "", "Path to Markdown output file")
	_ = fs.Parse(os.Args[2:])
	sql := mustRead(*queryPath, "--query is required")
	plan := ""
	if *explainPath != "" {
		plan = mustRead(*explainPath, "")
	}
	result := analyzer.Analyze(sql, plan)
	md := report.Markdown(result)
	if writeReport && *outputPath != "" {
		mustWrite(*outputPath, md)
		fmt.Println("Report written to", *outputPath)
		return
	}
	fmt.Print(md)
}

func runLint() {
	fs := flag.NewFlagSet("lint", flag.ExitOnError)
	queryPath := fs.String("query", "", "Path to SQL query file")
	_ = fs.Parse(os.Args[2:])
	sql := mustRead(*queryPath, "--query is required")
	result := analyzer.Analyze(sql, "")
	for _, f := range result.Findings {
		fmt.Printf("[%s] %s: %s\n", f.Severity, f.RuleID, f.Title)
	}
}

func runSuggestIndex() {
	fs := flag.NewFlagSet("suggest-index", flag.ExitOnError)
	queryPath := fs.String("query", "", "Path to SQL query file")
	_ = fs.Parse(os.Args[2:])
	sql := mustRead(*queryPath, "--query is required")
	result := analyzer.Analyze(sql, "")
	found := false
	for _, f := range result.Findings {
		for _, idx := range f.SuggestedIndexes {
			fmt.Println(idx)
			found = true
		}
	}
	if !found {
		fmt.Println("No index suggestion generated by current rule set.")
	}
}

func mustRead(path, errMsg string) string {
	if path == "" {
		fmt.Fprintln(os.Stderr, errMsg)
		os.Exit(2)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	return string(b)
}
func mustWrite(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
}
func usage() {
	fmt.Println(`PgQueryDoctor - PostgreSQL query analyzer

Usage:
  pgquerydoctor analyze --query query.sql --explain explain.txt
  pgquerydoctor report --query query.sql --explain explain.txt --output report.md
  pgquerydoctor lint --query query.sql
  pgquerydoctor suggest-index --query query.sql
  pgquerydoctor version`)
}
